### ISSUE TITLE
Contextmenu problem

### ISSUE THREAD

**Issue by xeno010** [diegocarloslima/FloatingGroupExpandableListView#10]
Hello,

I have registered  a context menu on the listview.

``` java
//Activity
listView = (FloatingGroupExpandableListView) view.findViewById(android.R.id.list);
registerForContextMenu(listView);
```
- Child-Items -> Works
- Group-Items position > 1 -> Works

Long press of the Frist Group-Item or Floating-Group-Items don't call the onCreateContextMenu. 

Have you a idea to solve the problem?

**Comment by diegocarloslima** [comment]
Hi xeno, thanks for the feedback. I'll take a look on this issue to see what I can do to fix it.

**Comment by diegocarloslima** [comment]
Done! :+1:
