### ISSUE TITLE
Android API 10 - no field "positionSelector"

### ISSUE THREAD

**Issue by KreoSoft** [diegocarloslima/FloatingGroupExpandableListView#11]
Hello.

On Android API 10 there is no field "positionSelector" in ExpandableListView class, so reflection doesn't work. There is no error, but there is a warning in log (see positionSelectorOnFloatingGroup method).
Anyway, this is a great library I was looking for!

Regards.

**Comment by diegocarloslima** [comment]
Hi KreoSoft. Thanks for reporting this issue. Currently I'm loaded of work, but this weekend I'll take a look on that.
