### ISSUE TITLE
1st Group not clickable/expandable

### ISSUE THREAD

**Issue by nemphys** [diegocarloslima/FloatingGroupExpandableListView#12]
Hi, I just discovered your library and I must say it is amazing!
One bug I found (except for the reflection errors in older API versions other people have mentioned) is that the first group header in my list does not expand when clicked (all other groups work well and as expected).
I have tried debugging the matter and it should not be happening, since the click is not dispatched to the floating group (as it shouldn't be) and it is passed to super.discpatchTouchEvent().
It seems that the floating header is actually picking up the click somehow, though.
Maybe it has something to do with my headers layout (they are simple horizontal linear layouts with android:clickable=false, having a textview and a button with a click handler as children).
Any suggestions would be appreciated...

**Comment by diegocarloslima** [comment]
Hi nemphys, thanks for the compliment. If possible, I would like you to send me by email a sample application code illustrating this issue. That way, will be easier to me to identify the problem.

**Comment by nemphys** [comment]
Hmm, I suppose that would required too much work, since all my data is received server-side and it is quite a complex setup.
Any other ideas?
I could try fiddling with the code if you point me to the right direction.

**Comment by diegocarloslima** [comment]
Well, you can place a breakpoint on line 312 to see if the condition is satisfied:

```
if(!mFloatingGroupView.isClickable()) {
        mSelectorEnabled = true;
        mFloatingGroupView.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                postDelayed(mOnClickAction, ViewConfiguration.getPressedStateDuration());
            }
        });
    }
```

And also on line 109 to see if the click action is being called:

```
mOnClickAction = new Runnable() {

    @Override
    public void run() {
        if(mAdapter.isGroupExpanded(mFloatingGroupPosition)) {
            collapseGroup(mFloatingGroupPosition);
        } else {
            expandGroup(mFloatingGroupPosition);
        }
        setSelectedGroup(mFloatingGroupPosition);
    }
};
```

**Comment by nemphys** [comment]
I actually already did that while debugging and 1) it is not clickable, so the listener is attached and 2) is never called for the first group (though it properly gets called for the rest).

**Comment by nemphys** [comment]
Sorry, my mistake: 2) is never called for any group, unless the floating header is visible (which is the correct behavior). It is not called for the first group at all, since it does not expand (so the floating group  header is never actually active for it).

**Comment by nemphys** [comment]
Found it: on line 303 the condition should be 
currentGroupView.getTop() >= getPaddingTop()
whereas on line 305, it should be
currentGroupView.getTop() < getPaddingTop() && currentGroupView.getVisibility() == View.VISIBLE

This makes sense, sine the first header view is at position 0 (i.e. == getPaddingTop()). In this case, it should not be set to invisible.

Now, if only it wouldn't crash on old API versions :-)

**Comment by diegocarloslima** [comment]
Hi again nemphys, the change you made uses the view attached to the ExpandableListView instead of the floating view at position = getPaddingTop(). I don't see whether this would fix the problem once the floating group should behave exactly as the original view. Does the click works when the first group is floating above its children?

**Comment by nemphys** [comment]
Yes, everything is working fine and as expected after the mentioned change.

**Comment by jobinj15** [comment]
I am unable to get the onchildclicklistener working. Please help
