### ISSUE TITLE
Gradle/Maven support

### ISSUE THREAD

**Issue by asgarddesigns** [diegocarloslima/FloatingGroupExpandableListView#18]
Would be great to be able to access this lib via a maven repo!

**Comment by diegocarloslima** [comment]
Done! :+1:

**Comment by asgarddesigns** [comment]
legendary... much appreciated!

**Comment by asgarddesigns** [comment]
Possibly worth adding a git tag for each release so we can track new changes as they are added :-)

**Comment by diegocarloslima** [comment]
Good idea Ben. I'll do that ;)

**Comment by 1zaman** [comment]
Could you please keep the Maven artifact up to date with the latest changes. You will have to either implement some versioning, or deploy snapshots. Thanks!

**Comment by mainer** [comment]
The object is so perfect after so many times modify。

## Thanks the author for giving us the project。

••• Zhang Qiang  
••• Android Developer of Sogou-inc 
••• From Beijing China  
••• zhangqiang120@gmail.com 
••• OR 247483276@qq.com
