### ISSUE TITLE
Pinned group view has changed height

### ISSUE THREAD

**Issue by AlexNab** [diegocarloslima/FloatingGroupExpandableListView#19]
Hi Diego,
At the moment group view may have different heights based on the state: pinned or not.
Imagine that we have group views with fixed height of 100dp (I've added a grey background to visualize group view bounds):
http://i.imgur.com/C2xEige.png - looks fine.

However, when the group view becomes pinned it will look like that:
http://i.imgur.com/ewyK4aB.png - as you can see group view height was changed!

**Steps to reproduce**
1. take the stock FloatingGroupExpandableListView sample
2. at _sample_activity_list_group_item.xml_ change root layout height from `android:layout_height="wrap_content"` to `android:layout_height="100dp"`. 
So we want to have fixed height to groups which is perfectly normal.
3. at _SampleAdapter.java_ change next line at _getGroupView_ method from:
`v = mLayoutInflater.inflate(R.layout.sample_activity_list_group_item, null);`
to
`v = mLayoutInflater.inflate(R.layout.sample_activity_list_group_item, parent, false);`

**Reason**
the real reason is how you inflate the group view at step 3. 
When we call _mLayoutInflater.inflate_ without _parent_ param inflater will ignores original layout params of the group layout (so we loose 100dp height). And seems the same you do when pin the group view, so it ignores initial view size and measure it as min height + paddings. Which is not fine. Group view should looks the same pinned and unpinned. 

You may want to read a good explanation of the proper layout inflater usage at:
http://www.doubleencore.com/2013/05/layout-inflation-as-intended/

Thanks

**Comment by diegocarloslima** [comment]
Hey AlexNab,
Thank you for your detailed explanation. I'll read the article you sent me and fix this problem asap.

**Comment by diegocarloslima** [comment]
Done! :+1:
