### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by imoblife** [diegocarloslima/FloatingGroupExpandableListView#26]
When I touched and begin to scroll, it just crashed.

java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
    at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.createFloatingGroupView(FloatingGroupExpandableListView.java:416)

**Comment by imoblife** [comment]
P.S. 4.4 is fine, but 2.3 isn't.

**Comment by imoblife** [comment]
I changed to this, and it works:

```
        // params = (AbsListView.LayoutParams) generateDefaultLayoutParams();
        params = (AbsListView.LayoutParams) new AbsListView.LayoutParams(
                AbsListView.LayoutParams.MATCH_PARENT,
                AbsListView.LayoutParams.WRAP_CONTENT, 0);  
```

**Comment by diegocarloslima** [comment]
Thank you for your contribution!
