### ISSUE TITLE
Image downloaded with Picasso disappears from the GroupView while scrolling

### ISSUE THREAD

**Issue by mehrad-rafigh** [diegocarloslima/FloatingGroupExpandableListView#31]
First of all thank you very much for this library, but I have an issue with the GroupView. When I download an Image to set on an ImageView in the GroupView, the downloaded Image disappears when I scroll down. When I scroll back to top, the Image is visible again. 
Did somebody experience that and has a clue why this keeps happening?
Thanks in regard!

**Comment by markmosleh** [comment]
hello diego, I am experiencing the same issue as the comment above , i am using adview android dfp within the group header... it is disappearing on scroll down and reappearing on scrolling back...any suggestions ?
