### ISSUE TITLE
Click animation for currentFloatingGroup

### ISSUE THREAD

**Issue by tfwalther** [diegocarloslima/FloatingGroupExpandableListView#5]
Hi,
happy new Year, too! And thanks for fixing bug #2 and #3. And now I can report the nect little bug: click-animations to views in the currentFloatingGroup are not supported and there is no click animation if you expand/collapse the current floating group. In your example activity the floating groups have usually a yellow background if they are clicked, but the floating group doesn't have this

**Comment by diegocarloslima** [comment]
Done! :+1:
