### ISSUE TITLE
Pinned group is not drawn after group expand

### ISSUE THREAD

**Issue by AlexNab** [diegocarloslima/FloatingGroupExpandableListView#6]
Hi Diego, thanks for your library! :-)
Seems there is a little issue with groups drawing as pinned.

Simple scenario to reproduce:
1. start list with several groups, all collapsed (as by default)
2. tap on the 2nd group will expand it, the list will scroll to show expanded 2nd group
3. now tap on the 2nd group again to collapse it... and you will expand the 1st group instead of collapsing the 2nd one in some cases.

Look at the attached image. 
![eyywye0](https://f.cloud.github.com/assets/1654855/1886809/642fcd0a-79ef-11e3-94fb-033fecc32752.png)
"MORE" is the 2nd group. And you can see a small piece of the 1st group bottom.
Tap anywhere inside the read area will expand the 1st group, even if visually you tap on the 2nd group. 
Red arrow points to the area which will invoke 1st group reaction, green arrow - 2nd group. Notice, that buggy area has height equal to group height.
So seems your library forgets to draw the 1st group as pinned (it should be pinned because it was moved to the top after the 2nd group expand at step 2), but thinks that it's here at reacts on taps appropriately.

What do you think about it?

**Comment by diegocarloslima** [comment]
Hi Alex, thanks for your feedback. I was able to reproduce this bug. It seems that when a group is expanded, a small portion of the previous one is still displayed and the floating group view position isn't updated. I'll work on this and update the lib as soon as possible.
