### ISSUE TITLE
Views are not converted properly

### ISSUE THREAD

**Issue by AlexNab** [diegocarloslima/FloatingGroupExpandableListView#7]
Seems there is a little flaw with views re-use at adapter.
Steps to reproduce:
1. run the library example 
2. collapse all groups
3. expand the last one (Android KitKat)
4. scroll up and down intensively several times. You will see that some groups are rendered in a wrong way. E.g. Cupcake and Eclair: 
   ![image 6](https://f.cloud.github.com/assets/1654855/1888154/6cf147e2-7a09-11e3-979f-e46e7c94e18c.png)

**Comment by diegocarloslima** [comment]
Hi again Alex. Good job finding this bug. It seems that at some point the adapter doesn't set back the visibility for the group view that was previously hidden in order to display the floating group. I'll check this too ;)
