### ISSUE TITLE
Item selection is lost after group expand/collapse

### ISSUE THREAD

**Issue by AlexNab** [diegocarloslima/FloatingGroupExpandableListView#9]
Hi! :-)
We can initialize the _FloatingGroupExpandableListView_ with the _listSelector_ to have list items highlighted on item click. However, that selection is lost after any group (even the group that doesn't hold the tapped item) expand/collapse.

I believe that the item selection should not be lost at group expanding/collapsing because expand/collapse is just a way of data visualization, while the data is the same (e.g. with one selected item).

What do you think about it?
Thanks

**Comment by diegocarloslima** [comment]
Hi Alex, I understand your point of view, but the lib is designed to keep as much as possible the behavior of the standard ExpandableListView. And for the standard ExpandableListView, once a item is clicked, the selection is lost.

**Comment by AlexNab** [comment]
Well, that makes sense!
However, you may want to add that feature (to persist selection) and make it disabled by default.
That way _FloatingGroupExpandableListView_ will behave as the standard _ExpandableListView_ by default. But if needed selection persistence could be enabled.

**Comment by diegocarloslima** [comment]
Hi again Alex. Well, for now I think that is a too specific request that wouldn't help most of the users of the lib. As a low priority request, I will leave that unimplemented until I receive enough requests to increase its priority. But for instance, you can fork the project and implement that if its useful for you. Thank you anyway for the suggestion :)

**Comment by AlexNab** [comment]
Hi Diego, no problem. :)
Thanks!
